#
# Recommend use for static configuration that does not change between environments.
#
# See also config/application.properties
#
isis:

  applib:
    annotation:
      action:
        explicit: true
      action-layout:
        css-class-fa:
          patterns:
            new.*:fa-plus,
            add.*:fa-plus-square,
            create.*:fa-plus,
            update.*:fa-edit,
            delete.*:fa-trash,
            find.*:fa-search,
            list.*:fa-list
        css-class:
          patterns:
            delete.*:btn-danger
      domain-object:
        editing: false

  core:
    meta-model:
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-object-type: true
        service-actions-only: true
        mixins-only: true

  viewer:
    wicket:
      application:
        menubars-layout-xml: domainapp/webapp/application/menubars.layout.xml
        brand-logo-header: /images/apache-isis/logo-48x48.png
        favicon-url: /images/favicon.png
        name: Hello World App
        css: css/application.css
        js: scripts/application.js
        about: Hello World

      credit:
        - url:  http://isis.apache.org
          image: /images/apache-isis/logo-48x48.png
          name: Apache Isis

      themes:
        initial: Flatly
        showChooser: true
        enabled: Cosmo,Flatly,Darkly,Sandstone,United

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      development-utilities:
        enable: true

  persistence:
    jdo-datanucleus:
      impl:
        # note that properties under 'isis.persistor.datanucleus.impl' are passed through directly
        # to DataNucleus, and must use camelCase rather than kebab-case
        datanucleus:
          schema:
            validateTables: true
            validateConstraints: true

          persistenceByReachabilityAtCommit: false
          identifier:
            case: MixedCase

          cache:
            level2:
              type: none
              mode: ENABLE_SELECTIVE

resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

spring:
  banner:
    location: banner.txt

